alias build="docker-compose build"
alias up="docker-compose up"
alias bundle="docker-compose run --rm app bundle"
alias rails="docker-compose run --rm app bundle exec rails"
alias yarn="docker-compose run --rm app yarn"